### ISSUE TITLE
define global attributes function

### ISSUE THREAD

**Issue by paolap** [ACCESS-Community-Hub/ACCESS-MOPPeR#141]
Add a define_attrs() function to add to attributes passed from user extra global attributes that might be needed to clarify variable. For example plevinterp() is setting NaN values outside the height range covered by the model levels and we want to highlight that as "notes".

**Comment by paolap** [comment]
I've added the function to mop_utils, it's reads notes from src/data/motes.yaml, which is easier to update than the code

```
notes:
     - calculation:
        - plevinterp: "Linearly interpolated from model levels using numpy.interp() function. NaNs are assigned to pressure levels falling out of the height range covered by the model"
     - variable_id:
         - ocontempdiff: "Include convection"
```
It checks if any of the keys listed for "fields" (like calculation etc) correspond to what's available in ctx.obj for that specific file.
For calculation it just checks if value is in "calculation" . Following example if plevinterp is in calculation, as the function details will vary.
